<?php
/**
 * Created by PhpStorm.
 * User: csepm_000
 * Date: 1/9/2017
 * Time: 10:20 AM
 */

return [
    'new_layout' => [
        ['home', 1], //home, rental office
        [2, 3], //Support Area, Support Step
        [4, 5, 6] //Company Profile, Privacy Policy, Contact
    ],


    "vn" => "https://vietnamhouse.jp/vi",
    "style.html" => "https://vietnamhouse.jp/support/style",
    "area.html" => "https://vietnamhouse.jp/support/area",
    "flow.html" => "https://vietnamhouse.jp/support/step",
    "faq.html" => "https://vietnamhouse.jp/support/help",
    "link.html" => "https://vietnamhouse.jp/support/link",
    "contact.html" => "https://vietnamhouse.jp/company/contact",
    "service.html" => "https://vietnamhouse.jp/support/option",
    "company.html" => "https://vietnamhouse.jp/company/profile",
    "owner.html" => "https://vietnamhouse.jp/support/landlord",
    "index.php?dispatch=products.search&advanced_filter=y" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=V24&variant_id=24" => "https://vietnamhouse.jp/category/district1",
    "index.php?dispatch=products.search&features_hash=V25&variant_id=25" => "https://vietnamhouse.jp/category/district2",
    "index.php?dispatch=products.search&features_hash=V26&variant_id=26" => "https://vietnamhouse.jp/category/district3",
    "index.php?dispatch=products.search&features_hash=V98&variant_id=98" => "https://vietnamhouse.jp/category/district4",
    "index.php?dispatch=products.search&features_hash=V319&variant_id=319" => "https://vietnamhouse.jp/category/district5",
    "index.php?dispatch=products.search&features_hash=V27&variant_id=27" => "https://vietnamhouse.jp/category/binh-thanh",
    "index.php?dispatch=products.search&features_hash=V28&variant_id=28" => "https://vietnamhouse.jp/category/district7",
    "index.php?dispatch=products.search&features_hash=V759&variant_id=759" => "https://vietnamhouse.jp/category/other-area",
    "index.php?dispatch=products.search&features_hash=V568&variant_id=568" => "https://vietnamhouse.jp/category/district10",
    "index.php?dispatch=products.search&features_hash=V30&variant_id=30" => "https://vietnamhouse.jp/category/phu-nhuan",
    "index.php?dispatch=products.search&features_hash=V36&variant_id=36" => "https://vietnamhouse.jp/category/tan-binh",
    "index.php?dispatch=products.search&features_hash=V648&variant_id=648" => "https://vietnamhouse.jp/category/other-area",
    "index.php?dispatch=products.search&features_hash=V12&variant_id=12" => "https://vietnamhouse.jp/category/villa",
    "index.php?dispatch=products.search&features_hash=V35&variant_id=35" => "https://vietnamhouse.jp/category/house",
//    "index.php?dispatch=products.search&features_hash=V10&variant_id=10" => "https://vietnamhouse.jp/category/condo",
    "index.php?dispatch=products.search&features_hash=V11&variant_id=11" => "https://vietnamhouse.jp/category/service-apt",
    "index.php?dispatch=products.search&features_hash=V13&variant_id=13" => "https://vietnamhouse.jp/category/office",
    "index.php?dispatch=products.search&features_hash=V543&variant_id=543" => "https://vietnamhouse.jp/category/house",
    "index.php?subcats=Y&status=A&pshort=Y&pfull=Y&pname=Y&pkeywords=Y&search_performed=Y&cid=0&features_hash=0&variant_id=0&q=&x=43&y=15&dispatch=products.search" => "https://vietnamhouse.jp/door",
    "index.php?dispatch=products.search&features_hash=P4&variant_id=4" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P2&variant_id=2" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P3&variant_id=3" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P5&variant_id=5" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P6&variant_id=6" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P7&variant_id=7" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P8&variant_id=8" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P9&variant_id=9" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P10&variant_id=10" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P11&variant_id=11" => "https://vietnamhouse.jp/search",
//    "index.php?dispatch=products.search&features_hash=V788&variant_id=788" => "https://vietnamhouse.jp/condo/pearl-plaza",
//    "index.php?dispatch=products.search&features_hash=V39&variant_id=39" => "https://vietnamhouse.jp/condo/manor",
//    "index.php?dispatch=products.search&features_hash=V153&variant_id=153" => "https://vietnamhouse.jp/condo/saigon-pearl",
//    "index.php?dispatch=products.search&features_hash=V569&variant_id=569" => "https://vietnamhouse.jp/condo/holizon",
//    "index.php?dispatch=products.search&features_hash=V561&variant_id=561" => "https://vietnamhouse.jp/condo/city-garden",
//    "index.php?dispatch=products.search&features_hash=V610&variant_id=610" => "https://vietnamhouse.jp/condo/thao-dien-pearl",
//    "index.php?dispatch=products.search&features_hash=V527&variant_id=527" => "https://vietnamhouse.jp/condo/estella",
//    "index.php?dispatch=products.search&features_hash=V139&variant_id=139" => "https://vietnamhouse.jp/condo/vista",
//    "index.php?dispatch=products.search&features_hash=V40&variant_id=40" => "https://vietnamhouse.jp/condo/avalon",
//    "index.php?dispatch=products.search&features_hash=V120&variant_id=120" => "https://vietnamhouse.jp/condo/lancaster",
//    "index.php?dispatch=products.search&features_hash=V41&variant_id=41" => "https://vietnamhouse.jp/condo/hoan-cau-cantavil",
//    "index.php?dispatch=products.search&features_hash=V176&variant_id=176" => "https://vietnamhouse.jp/condo/river-garden",
//    "index.php?dispatch=products.search&features_hash=V180&variant_id=180" => "https://vietnamhouse.jp/condo/xi-riverview-palace",
//    "index.php?dispatch=products.search&features_hash=V602&variant_id=602" => "https://vietnamhouse.jp/condo/fideco",
//    "index.php?dispatch=products.search&features_hash=V549&variant_id=549" => "https://vietnamhouse.jp/condo/imperia",
//    "index.php?dispatch=products.search&features_hash=V802&variant_id=802" => "https://vietnamhouse.jp/condo/lexington",
//    "index.php?dispatch=products.search&features_hash=V717&variant_id=717" => "https://vietnamhouse.jp/condo/diamond-island",
//    "index.php?dispatch=products.search&features_hash=V61&variant_id=61" => "https://vietnamhouse.jp/condo/sailing-tower",
//    "index.php?dispatch=products.search&features_hash=V106&variant_id=106" => "https://vietnamhouse.jp/condo/central-garden",
//    "index.php?dispatch=products.search&features_hash=V756&variant_id=756" => "https://vietnamhouse.jp/condo/sunrise-city",
//    "index.php?dispatch=products.search&features_hash=V67&variant_id=67" => "https://vietnamhouse.jp/condo/panorama",
//    "index.php?dispatch=products.search&features_hash=V772&variant_id=772" => "https://vietnamhouse.jp/condo/riviera-point",
//    "index.php?dispatch=products.search&features_hash=V305&variant_id=305" => "https://vietnamhouse.jp/condo/indochine-park",
//    "index.php?dispatch=products.search&features_hash=V190&variant_id=190" => "https://vietnamhouse.jp/condo/hoang-anh-gia-lai-d2",
//    "index.php?dispatch=products.search&features_hash=V572&variant_id=572" => "https://vietnamhouse.jp/condo/international-plaza",
//    "index.php?dispatch=products.search&features_hash=V605&variant_id=605" => "https://vietnamhouse.jp/condo/phu-nhuan-tower",
//    "index.php?dispatch=products.search&features_hash=V649&variant_id=649" => "https://vietnamhouse.jp/condo/celadon-city",
//    "index.php?dispatch=products.search&features_hash=V793&variant_id=793" => "https://vietnamhouse.jp/condo/happy-valley",
//    "index.php?dispatch=products.search&features_hash=V796&variant_id=796" => "https://vietnamhouse.jp/condo/star-hill",
//    "index.php?dispatch=products.search&features_hash=V812&variant_id=812" => "https://vietnamhouse.jp/condo/galaxy9",
//    "index.php?dispatch=products.search&features_hash=V807&variant_id=807" => "https://vietnamhouse.jp/condo/icon56",
//    "index.php?dispatch=products.search&features_hash=V809&variant_id=809" => "https://vietnamhouse.jp/condo/one-saigon",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820" => "https://vietnamhouse.jp/condo/prince",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820" => "https://vietnamhouse.jp/condo/ehome-5-the-bridgeview",
//    "index.php?dispatch=products.search&features_hash=V843&variant_id=843" => "https://vietnamhouse.jp/condo/vinhomes-central-park",
//    "index.php?dispatch=products.search&features_hash=V847&variant_id=847" => "https://vietnamhouse.jp/condo/vincom-center",
//    "index.php?dispatch=products.search&features_hash=V840&variant_id=840" => "https://vietnamhouse.jp/condo/sala",
    "en/style-en.html" => "https://vietnamhouse.jp/en/support/style",
    "en/area-en.html" => "https://vietnamhouse.jp/en/support/area",
    "en/flow-en.html" => "https://vietnamhouse.jp/en/support/step",
    "en/faq-en.html" => "https://vietnamhouse.jp/en/support/help",
    "en/en-2-3-4-5-6-7-8.html" => "https://vietnamhouse.jp/en/support/link",
    "en/contact-en.html" => "https://vietnamhouse.jp/en/company/contact",
    "en/service-en.html" => "https://vietnamhouse.jp/en/support/option",
    "en/company-en.html" => "https://vietnamhouse.jp/en/company/profile",
    "en/owner-en.html" => "https://vietnamhouse.jp/en/support/landlord",
    "index.php?dispatch=products.search&advanced_filter=y&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=V24&variant_id=24&sl=EN" => "https://vietnamhouse.jp/en/category/district1",
    "index.php?dispatch=products.search&features_hash=V25&variant_id=25&sl=EN" => "https://vietnamhouse.jp/en/category/district2",
    "index.php?dispatch=products.search&features_hash=V26&variant_id=26&sl=EN" => "https://vietnamhouse.jp/en/category/district3",
    "index.php?dispatch=products.search&features_hash=V98&variant_id=98&sl=EN" => "https://vietnamhouse.jp/en/category/district4",
    "index.php?dispatch=products.search&features_hash=V319&variant_id=319&sl=EN" => "https://vietnamhouse.jp/en/category/district5",
    "index.php?dispatch=products.search&features_hash=V27&variant_id=27&sl=EN" => "https://vietnamhouse.jp/en/category/binh-thanh",
    "index.php?dispatch=products.search&features_hash=V28&variant_id=28&sl=EN" => "https://vietnamhouse.jp/en/category/district7",
    "index.php?dispatch=products.search&features_hash=V759&variant_id=759&sl=EN" => "https://vietnamhouse.jp/en/category/other-area",
    "index.php?dispatch=products.search&features_hash=V568&variant_id=568&sl=EN" => "https://vietnamhouse.jp/en/category/district10",
    "index.php?dispatch=products.search&features_hash=V30&variant_id=30&sl=EN" => "https://vietnamhouse.jp/en/category/phu-nhuan",
    "index.php?dispatch=products.search&features_hash=V36&variant_id=36&sl=EN" => "https://vietnamhouse.jp/en/category/tan-binh",
    "index.php?dispatch=products.search&features_hash=V648&variant_id=648&sl=EN" => "https://vietnamhouse.jp/en/category/other-area",
    "index.php?dispatch=products.search&features_hash=V12&variant_id=12&sl=EN" => "https://vietnamhouse.jp/en/category/villa",
    "index.php?dispatch=products.search&features_hash=V35&variant_id=35&sl=EN" => "https://vietnamhouse.jp/en/category/house",
//    "index.php?dispatch=products.search&features_hash=V10&variant_id=10&sl=EN" => "https://vietnamhouse.jp/en/category/condo",
    "index.php?dispatch=products.search&features_hash=V11&variant_id=11&sl=EN" => "https://vietnamhouse.jp/en/category/service-apt",
    "index.php?dispatch=products.search&features_hash=V13&variant_id=13&sl=EN" => "https://vietnamhouse.jp/en/category/office",
    "index.php?dispatch=products.search&features_hash=V543&variant_id=543&sl=EN" => "https://vietnamhouse.jp/en/category/house",
    "index.php?subcats=Y&status=A&pshort=Y&pfull=Y&pname=Y&pkeywords=Y&search_performed=Y&cid=0&features_hash=0&variant_id=0&q=&x=43&y=15&dispatch=products.search&sl=EN" => "https://vietnamhouse.jp/en/office",
    "index.php?dispatch=products.search&features_hash=P4&variant_id=4&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P2&variant_id=2&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P3&variant_id=3&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P5&variant_id=5&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P6&variant_id=6&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P7&variant_id=7&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P8&variant_id=8&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P9&variant_id=9&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P10&variant_id=10&sl=EN" => "https://vietnamhouse.jp/en/search",
    "index.php?dispatch=products.search&features_hash=P11&variant_id=11&sl=EN" => "https://vietnamhouse.jp/en/search",
//    "index.php?dispatch=products.search&features_hash=V788&variant_id=788&sl=EN" => "https://vietnamhouse.jp/en/condo/pearl-plaza",
//    "index.php?dispatch=products.search&features_hash=V39&variant_id=39&sl=EN" => "https://vietnamhouse.jp/en/condo/manor",
//    "index.php?dispatch=products.search&features_hash=V153&variant_id=153&sl=EN" => "https://vietnamhouse.jp/en/condo/saigon-pearl",
//    "index.php?dispatch=products.search&features_hash=V569&variant_id=569&sl=EN" => "https://vietnamhouse.jp/en/condo/holizon",
//    "index.php?dispatch=products.search&features_hash=V561&variant_id=561&sl=EN" => "https://vietnamhouse.jp/en/condo/city-garden",
//    "index.php?dispatch=products.search&features_hash=V610&variant_id=610&sl=EN" => "https://vietnamhouse.jp/en/condo/thao-dien-pearl",
//    "index.php?dispatch=products.search&features_hash=V527&variant_id=527&sl=EN" => "https://vietnamhouse.jp/en/condo/estella",
//    "index.php?dispatch=products.search&features_hash=V139&variant_id=139&sl=EN" => "https://vietnamhouse.jp/en/condo/vista",
//    "index.php?dispatch=products.search&features_hash=V40&variant_id=40&sl=EN" => "https://vietnamhouse.jp/en/condo/avalon",
//    "index.php?dispatch=products.search&features_hash=V120&variant_id=120&sl=EN" => "https://vietnamhouse.jp/en/condo/lancaster",
//    "index.php?dispatch=products.search&features_hash=V41&variant_id=41&sl=EN" => "https://vietnamhouse.jp/en/condo/hoan-cau-cantavil",
//    "index.php?dispatch=products.search&features_hash=V176&variant_id=176&sl=EN" => "https://vietnamhouse.jp/en/condo/river-garden",
//    "index.php?dispatch=products.search&features_hash=V180&variant_id=180&sl=EN" => "https://vietnamhouse.jp/en/condo/xi-riverview-palace",
//    "index.php?dispatch=products.search&features_hash=V602&variant_id=602&sl=EN" => "https://vietnamhouse.jp/en/condo/fideco",
//    "index.php?dispatch=products.search&features_hash=V549&variant_id=549&sl=EN" => "https://vietnamhouse.jp/en/condo/imperia",
//    "index.php?dispatch=products.search&features_hash=V802&variant_id=802&sl=EN" => "https://vietnamhouse.jp/en/condo/lexington",
//    "index.php?dispatch=products.search&features_hash=V717&variant_id=717&sl=EN" => "https://vietnamhouse.jp/en/condo/diamond-island",
//    "index.php?dispatch=products.search&features_hash=V61&variant_id=61&sl=EN" => "https://vietnamhouse.jp/en/condo/sailing-tower",
//    "index.php?dispatch=products.search&features_hash=V106&variant_id=106&sl=EN" => "https://vietnamhouse.jp/en/condo/central-garden",
//    "index.php?dispatch=products.search&features_hash=V756&variant_id=756&sl=EN" => "https://vietnamhouse.jp/en/condo/sunrise-city",
//    "index.php?dispatch=products.search&features_hash=V67&variant_id=67&sl=EN" => "https://vietnamhouse.jp/en/condo/panorama",
//    "index.php?dispatch=products.search&features_hash=V772&variant_id=772&sl=EN" => "https://vietnamhouse.jp/en/condo/riviera-point",
//    "index.php?dispatch=products.search&features_hash=V305&variant_id=305&sl=EN" => "https://vietnamhouse.jp/en/condo/indochine-park",
//    "index.php?dispatch=products.search&features_hash=V190&variant_id=190&sl=EN" => "https://vietnamhouse.jp/en/condo/hoang-anh-gia-lai-d2",
//    "index.php?dispatch=products.search&features_hash=V572&variant_id=572&sl=EN" => "https://vietnamhouse.jp/en/condo/international-plaza",
//    "index.php?dispatch=products.search&features_hash=V605&variant_id=605&sl=EN" => "https://vietnamhouse.jp/en/condo/phu-nhuan-tower",
//    "index.php?dispatch=products.search&features_hash=V649&variant_id=649&sl=EN" => "https://vietnamhouse.jp/en/condo/celadon-city",
//    "index.php?dispatch=products.search&features_hash=V793&variant_id=793&sl=EN" => "https://vietnamhouse.jp/en/condo/happy-valley",
//    "index.php?dispatch=products.search&features_hash=V796&variant_id=796&sl=EN" => "https://vietnamhouse.jp/en/condo/star-hill",
//    "index.php?dispatch=products.search&features_hash=V812&variant_id=812&sl=EN" => "https://vietnamhouse.jp/en/condo/galaxy9",
//    "index.php?dispatch=products.search&features_hash=V807&variant_id=807&sl=EN" => "https://vietnamhouse.jp/en/condo/icon56",
//    "index.php?dispatch=products.search&features_hash=V809&variant_id=809&sl=EN" => "https://vietnamhouse.jp/en/condo/one-saigon",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820&sl=EN" => "https://vietnamhouse.jp/en/condo/prince",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820&sl=EN" => "https://vietnamhouse.jp/en/condo/ehome-5-the-bridgeview",
//    "index.php?dispatch=products.search&features_hash=V843&variant_id=843&sl=EN" => "https://vietnamhouse.jp/en/condo/vinhomes-central-park",
//    "index.php?dispatch=products.search&features_hash=V847&variant_id=847&sl=EN" => "https://vietnamhouse.jp/en/condo/vincom-center",
//    "index.php?dispatch=products.search&features_hash=V840&variant_id=840&sl=EN" => "https://vietnamhouse.jp/en/condo/sala",
    "vn/style-vn.html" => "https://vietnamhouse.jp/vi/support/style",
    "vn/area-vn.html" => "https://vietnamhouse.jp/vi/support/area",
    "vn/flow-vn.html" => "https://vietnamhouse.jp/vi/support/step",
    "vn/faq-vn.html" => "https://vietnamhouse.jp/vi/support/help",
    "vn/page-24.html" => "https://vietnamhouse.jp/vi/support/link",
    "vn/contact-vn.html" => "https://vietnamhouse.jp/vi/company/contact",
    "vn/about-us.html" => "https://vietnamhouse.jp/vi/support/option",
    "vn/company-info.html" => "https://vietnamhouse.jp/vi/company/profile",
    "vn/for-properties-owner.html" => "https://vietnamhouse.jp/vi/support/landlord",
    "index.php?dispatch=products.search&advanced_filter=y&sl=VN" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=V24&variant_id=24&sl=VN" => "https://vietnamhouse.jp/vi/category/district1",
    "index.php?dispatch=products.search&features_hash=V25&variant_id=25&sl=VN" => "https://vietnamhouse.jp/vi/category/district2",
    "index.php?dispatch=products.search&features_hash=V26&variant_id=26&sl=VN" => "https://vietnamhouse.jp/vi/category/district3",
    "index.php?dispatch=products.search&features_hash=V98&variant_id=98&sl=VN" => "https://vietnamhouse.jp/vi/category/district4",
    "index.php?dispatch=products.search&features_hash=V319&variant_id=319&sl=VN" => "https://vietnamhouse.jp/vi/category/district5",
    "index.php?dispatch=products.search&features_hash=V27&variant_id=27&sl=VN" => "https://vietnamhouse.jp/vi/category/binh-thanh",
    "index.php?dispatch=products.search&features_hash=V28&variant_id=28&sl=VN" => "https://vietnamhouse.jp/vi/category/district7",
    "index.php?dispatch=products.search&features_hash=V759&variant_id=759&sl=VN" => "https://vietnamhouse.jp/vi/category/other-area",
    "index.php?dispatch=products.search&features_hash=V568&variant_id=568&sl=VN" => "https://vietnamhouse.jp/vi/category/district10",
    "index.php?dispatch=products.search&features_hash=V30&variant_id=30&sl=VN" => "https://vietnamhouse.jp/vi/category/phu-nhuan",
    "index.php?dispatch=products.search&features_hash=V36&variant_id=36&sl=VN" => "https://vietnamhouse.jp/vi/category/tan-binh",
    "index.php?dispatch=products.search&features_hash=V648&variant_id=648&sl=VN" => "https://vietnamhouse.jp/vi/category/other-area",
    "index.php?dispatch=products.search&features_hash=V12&variant_id=12&sl=VN" => "https://vietnamhouse.jp/vi/category/villa",
    "index.php?dispatch=products.search&features_hash=V35&variant_id=35&sl=VN" => "https://vietnamhouse.jp/vi/category/house",
//    "index.php?dispatch=products.search&features_hash=V10&variant_id=10&sl=VN" => "https://vietnamhouse.jp/vi/category/condo",
    "index.php?dispatch=products.search&features_hash=V11&variant_id=11&sl=VN" => "https://vietnamhouse.jp/vi/category/service-apt",
    "index.php?dispatch=products.search&features_hash=V13&variant_id=13&sl=VN" => "https://vietnamhouse.jp/vi/category/office",
    "index.php?dispatch=products.search&features_hash=V543&variant_id=543&sl=VN" => "https://vietnamhouse.jp/vi/category/house",
    "index.php?subcats=Y&status=A&pshort=Y&pfull=Y&pname=Y&pkeywords=Y&search_performed=Y&cid=0&features_hash=0&variant_id=0&q=&x=43&y=15&dispatch=products.search&sl=VN" => "https://vietnamhouse.jp/vi/office",
    "index.php?dispatch=products.search&features_hash=P4&variant_id=4" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P2&variant_id=2" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P3&variant_id=3" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P5&variant_id=5" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P6&variant_id=6" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P7&variant_id=7" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P8&variant_id=8" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P9&variant_id=9" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P10&variant_id=10" => "https://vietnamhouse.jp/vi/search",
    "index.php?dispatch=products.search&features_hash=P11&variant_id=11" => "https://vietnamhouse.jp/vi/search",
//    "index.php?dispatch=products.search&features_hash=V788&variant_id=788" => "https://vietnamhouse.jp/vi/condo/pearl-plaza",
//    "index.php?dispatch=products.search&features_hash=V39&variant_id=39" => "https://vietnamhouse.jp/vi/condo/manor",
//    "index.php?dispatch=products.search&features_hash=V153&variant_id=153" => "https://vietnamhouse.jp/vi/condo/saigon-pearl",
//    "index.php?dispatch=products.search&features_hash=V569&variant_id=569" => "https://vietnamhouse.jp/vi/condo/holizon",
//    "index.php?dispatch=products.search&features_hash=V561&variant_id=561" => "https://vietnamhouse.jp/vi/condo/city-garden",
//    "index.php?dispatch=products.search&features_hash=V610&variant_id=610" => "https://vietnamhouse.jp/vi/condo/thao-dien-pearl",
//    "index.php?dispatch=products.search&features_hash=V527&variant_id=527" => "https://vietnamhouse.jp/vi/condo/estella",
//    "index.php?dispatch=products.search&features_hash=V139&variant_id=139" => "https://vietnamhouse.jp/vi/condo/vista",
//    "index.php?dispatch=products.search&features_hash=V40&variant_id=40" => "https://vietnamhouse.jp/vi/condo/avalon",
//    "index.php?dispatch=products.search&features_hash=V120&variant_id=120" => "https://vietnamhouse.jp/vi/condo/lancaster",
//    "index.php?dispatch=products.search&features_hash=V41&variant_id=41" => "https://vietnamhouse.jp/vi/condo/hoan-cau-cantavil",
//    "index.php?dispatch=products.search&features_hash=V176&variant_id=176" => "https://vietnamhouse.jp/vi/condo/river-garden",
//    "index.php?dispatch=products.search&features_hash=V180&variant_id=180" => "https://vietnamhouse.jp/vi/condo/xi-riverview-palace",
//    "index.php?dispatch=products.search&features_hash=V602&variant_id=602" => "https://vietnamhouse.jp/vi/condo/fideco",
//    "index.php?dispatch=products.search&features_hash=V549&variant_id=549" => "https://vietnamhouse.jp/vi/condo/imperia",
//    "index.php?dispatch=products.search&features_hash=V802&variant_id=802" => "https://vietnamhouse.jp/vi/condo/lexington",
//    "index.php?dispatch=products.search&features_hash=V717&variant_id=717" => "https://vietnamhouse.jp/vi/condo/diamond-island",
//    "index.php?dispatch=products.search&features_hash=V61&variant_id=61" => "https://vietnamhouse.jp/vi/condo/sailing-tower",
//    "index.php?dispatch=products.search&features_hash=V106&variant_id=106" => "https://vietnamhouse.jp/vi/condo/central-garden",
//    "index.php?dispatch=products.search&features_hash=V756&variant_id=756" => "https://vietnamhouse.jp/vi/condo/sunrise-city",
//    "index.php?dispatch=products.search&features_hash=V67&variant_id=67" => "https://vietnamhouse.jp/vi/condo/panorama",
//    "index.php?dispatch=products.search&features_hash=V772&variant_id=772" => "https://vietnamhouse.jp/vi/condo/riviera-point",
//    "index.php?dispatch=products.search&features_hash=V305&variant_id=305" => "https://vietnamhouse.jp/vi/condo/indochine-park",
//    "index.php?dispatch=products.search&features_hash=V190&variant_id=190" => "https://vietnamhouse.jp/vi/condo/hoang-anh-gia-lai-d2",
//    "index.php?dispatch=products.search&features_hash=V572&variant_id=572" => "https://vietnamhouse.jp/vi/condo/international-plaza",
//    "index.php?dispatch=products.search&features_hash=V605&variant_id=605" => "https://vietnamhouse.jp/vi/condo/phu-nhuan-tower",
//    "index.php?dispatch=products.search&features_hash=V649&variant_id=649" => "https://vietnamhouse.jp/vi/condo/celadon-city",
//    "index.php?dispatch=products.search&features_hash=V793&variant_id=793" => "https://vietnamhouse.jp/vi/condo/happy-valley",
//    "index.php?dispatch=products.search&features_hash=V796&variant_id=796" => "https://vietnamhouse.jp/vi/condo/star-hill",
//    "index.php?dispatch=products.search&features_hash=V812&variant_id=812" => "https://vietnamhouse.jp/vi/condo/galaxy9",
//    "index.php?dispatch=products.search&features_hash=V807&variant_id=807" => "https://vietnamhouse.jp/vi/condo/icon56",
//    "index.php?dispatch=products.search&features_hash=V809&variant_id=809" => "https://vietnamhouse.jp/vi/condo/one-saigon",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820" => "https://vietnamhouse.jp/vi/condo/prince",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820" => "https://vietnamhouse.jp/vi/condo/ehome-5-the-bridgeview",
//    "index.php?dispatch=products.search&features_hash=V843&variant_id=843" => "https://vietnamhouse.jp/vi/condo/vinhomes-central-park",
//    "index.php?dispatch=products.search&features_hash=V847&variant_id=847" => "https://vietnamhouse.jp/vi/condo/vincom-center",
//    "index.php?dispatch=products.search&features_hash=V840&variant_id=840" => "https://vietnamhouse.jp/vi/condo/sala",
    "index.php?dispatch=products.search&advanced_filter=y&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=V24&variant_id=24&sl=JP" => "https://vietnamhouse.jp/category/district1",
    "index.php?dispatch=products.search&features_hash=V25&variant_id=25&sl=JP" => "https://vietnamhouse.jp/category/district2",
    "index.php?dispatch=products.search&features_hash=V26&variant_id=26&sl=JP" => "https://vietnamhouse.jp/category/district3",
    "index.php?dispatch=products.search&features_hash=V98&variant_id=98&sl=JP" => "https://vietnamhouse.jp/category/district4",
    "index.php?dispatch=products.search&features_hash=V319&variant_id=319&sl=JP" => "https://vietnamhouse.jp/category/district5",
    "index.php?dispatch=products.search&features_hash=V27&variant_id=27&sl=JP" => "https://vietnamhouse.jp/category/binh-thanh",
    "index.php?dispatch=products.search&features_hash=V28&variant_id=28&sl=JP" => "https://vietnamhouse.jp/category/district7",
    "index.php?dispatch=products.search&features_hash=V759&variant_id=759&sl=JP" => "https://vietnamhouse.jp/category/other-area",
    "index.php?dispatch=products.search&features_hash=V568&variant_id=568&sl=JP" => "https://vietnamhouse.jp/category/district10",
    "index.php?dispatch=products.search&features_hash=V30&variant_id=30&sl=JP" => "https://vietnamhouse.jp/category/phu-nhuan",
    "index.php?dispatch=products.search&features_hash=V36&variant_id=36&sl=JP" => "https://vietnamhouse.jp/category/tan-binh",
    "index.php?dispatch=products.search&features_hash=V648&variant_id=648&sl=JP" => "https://vietnamhouse.jp/category/other-area",
    "index.php?dispatch=products.search&features_hash=V12&variant_id=12&sl=JP" => "https://vietnamhouse.jp/category/villa",
    "index.php?dispatch=products.search&features_hash=V35&variant_id=35&sl=JP" => "https://vietnamhouse.jp/category/house",
//    "index.php?dispatch=products.search&features_hash=V10&variant_id=10&sl=JP" => "https://vietnamhouse.jp/category/condo",
    "index.php?dispatch=products.search&features_hash=V11&variant_id=11&sl=JP" => "https://vietnamhouse.jp/category/service-apt",
    "index.php?dispatch=products.search&features_hash=V13&variant_id=13&sl=JP" => "https://vietnamhouse.jp/category/office",
    "index.php?dispatch=products.search&features_hash=V543&variant_id=543&sl=JP" => "https://vietnamhouse.jp/category/house",
    "index.php?subcats=Y&status=A&pshort=Y&pfull=Y&pname=Y&pkeywords=Y&search_performed=Y&cid=0&features_hash=0&variant_id=0&q=&x=43&y=15&dispatch=products.search&sl=JP" => "https://vietnamhouse.jp/office",
    "index.php?dispatch=products.search&features_hash=P4&variant_id=4&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P2&variant_id=2&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P3&variant_id=3&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P5&variant_id=5&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P6&variant_id=6&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P7&variant_id=7&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P8&variant_id=8&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P9&variant_id=9&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P10&variant_id=10&sl=JP" => "https://vietnamhouse.jp/search",
    "index.php?dispatch=products.search&features_hash=P11&variant_id=11&sl=JP" => "https://vietnamhouse.jp/search",
//    "index.php?dispatch=products.search&features_hash=V788&variant_id=788&sl=JP" => "https://vietnamhouse.jp/condo/pearl-plaza",
//    "index.php?dispatch=products.search&features_hash=V39&variant_id=39&sl=JP" => "https://vietnamhouse.jp/condo/manor",
//    "index.php?dispatch=products.search&features_hash=V153&variant_id=153&sl=JP" => "https://vietnamhouse.jp/condo/saigon-pearl",
//    "index.php?dispatch=products.search&features_hash=V569&variant_id=569&sl=JP" => "https://vietnamhouse.jp/condo/holizon",
//    "index.php?dispatch=products.search&features_hash=V561&variant_id=561&sl=JP" => "https://vietnamhouse.jp/condo/city-garden",
//    "index.php?dispatch=products.search&features_hash=V610&variant_id=610&sl=JP" => "https://vietnamhouse.jp/condo/thao-dien-pearl",
//    "index.php?dispatch=products.search&features_hash=V527&variant_id=527&sl=JP" => "https://vietnamhouse.jp/condo/estella",
//    "index.php?dispatch=products.search&features_hash=V139&variant_id=139&sl=JP" => "https://vietnamhouse.jp/condo/vista",
//    "index.php?dispatch=products.search&features_hash=V40&variant_id=40&sl=JP" => "https://vietnamhouse.jp/condo/avalon",
//    "index.php?dispatch=products.search&features_hash=V120&variant_id=120&sl=JP" => "https://vietnamhouse.jp/condo/lancaster",
//    "index.php?dispatch=products.search&features_hash=V41&variant_id=41&sl=JP" => "https://vietnamhouse.jp/condo/hoan-cau-cantavil",
//    "index.php?dispatch=products.search&features_hash=V176&variant_id=176&sl=JP" => "https://vietnamhouse.jp/condo/river-garden",
//    "index.php?dispatch=products.search&features_hash=V180&variant_id=180&sl=JP" => "https://vietnamhouse.jp/condo/xi-riverview-palace",
//    "index.php?dispatch=products.search&features_hash=V602&variant_id=602&sl=JP" => "https://vietnamhouse.jp/condo/fideco",
//    "index.php?dispatch=products.search&features_hash=V549&variant_id=549&sl=JP" => "https://vietnamhouse.jp/condo/imperia",
//    "index.php?dispatch=products.search&features_hash=V802&variant_id=802&sl=JP" => "https://vietnamhouse.jp/condo/lexington",
//    "index.php?dispatch=products.search&features_hash=V717&variant_id=717&sl=JP" => "https://vietnamhouse.jp/condo/diamond-island",
//    "index.php?dispatch=products.search&features_hash=V61&variant_id=61&sl=JP" => "https://vietnamhouse.jp/condo/sailing-tower",
//    "index.php?dispatch=products.search&features_hash=V106&variant_id=106&sl=JP" => "https://vietnamhouse.jp/condo/central-garden",
//    "index.php?dispatch=products.search&features_hash=V756&variant_id=756&sl=JP" => "https://vietnamhouse.jp/condo/sunrise-city",
//    "index.php?dispatch=products.search&features_hash=V67&variant_id=67&sl=JP" => "https://vietnamhouse.jp/condo/panorama",
//    "index.php?dispatch=products.search&features_hash=V772&variant_id=772&sl=JP" => "https://vietnamhouse.jp/condo/riviera-point",
//    "index.php?dispatch=products.search&features_hash=V305&variant_id=305&sl=JP" => "https://vietnamhouse.jp/condo/indochine-park",
//    "index.php?dispatch=products.search&features_hash=V190&variant_id=190&sl=JP" => "https://vietnamhouse.jp/condo/hoang-anh-gia-lai-d2",
//    "index.php?dispatch=products.search&features_hash=V572&variant_id=572&sl=JP" => "https://vietnamhouse.jp/condo/international-plaza",
//    "index.php?dispatch=products.search&features_hash=V605&variant_id=605&sl=JP" => "https://vietnamhouse.jp/condo/phu-nhuan-tower",
//    "index.php?dispatch=products.search&features_hash=V649&variant_id=649&sl=JP" => "https://vietnamhouse.jp/condo/celadon-city",
//    "index.php?dispatch=products.search&features_hash=V793&variant_id=793&sl=JP" => "https://vietnamhouse.jp/condo/happy-valley",
//    "index.php?dispatch=products.search&features_hash=V796&variant_id=796&sl=JP" => "https://vietnamhouse.jp/condo/star-hill",
//    "index.php?dispatch=products.search&features_hash=V812&variant_id=812&sl=JP" => "https://vietnamhouse.jp/condo/galaxy9",
//    "index.php?dispatch=products.search&features_hash=V807&variant_id=807&sl=JP" => "https://vietnamhouse.jp/condo/icon56",
//    "index.php?dispatch=products.search&features_hash=V809&variant_id=809&sl=JP" => "https://vietnamhouse.jp/condo/one-saigon",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820&sl=JP" => "https://vietnamhouse.jp/condo/prince",
//    "index.php?dispatch=products.search&features_hash=V820&variant_id=820&sl=JP" => "https://vietnamhouse.jp/condo/ehome-5-the-bridgeview",
//    "index.php?dispatch=products.search&features_hash=V843&variant_id=843&sl=JP" => "https://vietnamhouse.jp/condo/vinhomes-central-park",
//    "index.php?dispatch=products.search&features_hash=V847&variant_id=847&sl=JP" => "https://vietnamhouse.jp/condo/vincom-center",
//    "index.php?dispatch=products.search&features_hash=V840&variant_id=840&sl=JP" => "https://vietnamhouse.jp/condo/sala",
];